"""empty message

Revision ID: 189c3ddefc94
Revises: f3f686c995bd
Create Date: 2023-01-26 14:44:20.289026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189c3ddefc94'
down_revision = 'f3f686c995bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('single__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('single__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
